services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: lumi
      POSTGRES_PASSWORD: lumipass
      POSTGRES_DB: lumidb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
